//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eBuyDBEntities : DbContext
    {
        public eBuyDBEntities()
            : base("name=eBuyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<InStorePayment> InStorePayments { get; set; }
        public virtual DbSet<InStoreSale> InStoreSales { get; set; }
        public virtual DbSet<InStoreSaleDetail> InStoreSaleDetails { get; set; }
        public virtual DbSet<InStoreSaleInvoice> InStoreSaleInvoices { get; set; }
        public virtual DbSet<InStoreWarranty> InStoreWarranties { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<OnlineListing> OnlineListings { get; set; }
        public virtual DbSet<OnlineListingBySupplier> OnlineListingBySuppliers { get; set; }
        public virtual DbSet<OnlineListingOwn> OnlineListingOwns { get; set; }
        public virtual DbSet<OnlinePayment> OnlinePayments { get; set; }
        public virtual DbSet<OnlineSale> OnlineSales { get; set; }
        public virtual DbSet<OnlineSaleDetail> OnlineSaleDetails { get; set; }
        public virtual DbSet<OnlineSaleInvoice> OnlineSaleInvoices { get; set; }
        public virtual DbSet<OnlineWarranty> OnlineWarranties { get; set; }
        public virtual DbSet<OnlineWarrantyClaim> OnlineWarrantyClaims { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
