//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class InStoreWarranty
    {
        public int Id { get; set; }
        public int IdInStoreSaleDetail { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string WarrantyStatus { get; set; }

        [JsonIgnore]
        public virtual InStoreSaleDetail InStoreSaleDetail { get; set; }
    }
}
