//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InStoreSaleInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InStoreSaleInvoice()
        {
            this.InStorePayments = new HashSet<InStorePayment>();
        }
    
        public int Id { get; set; }
        public int IdInStoreSale { get; set; }
        public decimal TotalAmount { get; set; }
        public int InvoiceNumber { get; set; }
        public string PaymentMethod { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InStorePayment> InStorePayments { get; set; }
        public virtual InStoreSale InStoreSale { get; set; }
    }
}
