//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineSaleInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineSaleInvoice()
        {
            this.OnlinePayments = new HashSet<OnlinePayment>();
        }
    
        public int Id { get; set; }
        public int IdOnlineSale { get; set; }
        public decimal TotalAmount { get; set; }
        public int InvoiceNumber { get; set; }
        public string PaymentMethod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<OnlinePayment> OnlinePayments { get; set; }
        [JsonIgnore]
        public virtual OnlineSale OnlineSale { get; set; }
    }
}
