//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineListingBySupplier
    {
        public int Id { get; set; }
        public int IdOnlineListing { get; set; }
        public int IdSupplier { get; set; }
        public string SupplierName { get; set; }
        public string SupplierEmail { get; set; }
        public int SupplierPhone { get; set; }
    
        public virtual OnlineListing OnlineListing { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
