//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class OnlinePayment
    {
        public int Id { get; set; }
        public int IdOnlineSaleInvoice { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethod { get; set; }
        public int ReferenceNumber { get; set; }
        public string PaymentStatus { get; set; }

        [JsonIgnore]
        public virtual OnlineSaleInvoice OnlineSaleInvoice { get; set; }
    }
}
