//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineWarrantyClaim
    {
        public int Id { get; set; }
        public int IdOnlineWarranty { get; set; }
        public System.DateTime ClaimDate { get; set; }
        public System.DateTime ResolutionDate { get; set; }
        public string Resolution { get; set; }
        public string TechnicalNotes { get; set; }
    
        public virtual OnlineWarranty OnlineWarranty { get; set; }
    }
}
