//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineSale()
        {
            this.OnlineSaleDetails = new HashSet<OnlineSaleDetail>();
            this.OnlineSaleInvoices = new HashSet<OnlineSaleInvoice>();
        }
    
        public int Id { get; set; }
        public int IdSale { get; set; }
        public bool PaymentStatus { get; set; }
        public int TrackingNumber { get; set; }
        public string ShippingAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineSaleDetail> OnlineSaleDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineSaleInvoice> OnlineSaleInvoices { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
