//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineListingOwn
    {
        public int Id { get; set; }
        public int IdOnlineListing { get; set; }
        public int IdEmployee { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAssignedBranch { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual OnlineListing OnlineListing { get; set; }
    }
}
