//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineWarranty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineWarranty()
        {
            this.OnlineWarrantyClaims = new HashSet<OnlineWarrantyClaim>();
        }
    
        public int Id { get; set; }
        public int IdOnlineSaleDetail { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ClaimReason { get; set; }
        public string Resolution { get; set; }
        public string WarrantyStatus { get; set; }
    
        public virtual OnlineSaleDetail OnlineSaleDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineWarrantyClaim> OnlineWarrantyClaims { get; set; }
    }
}
