//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuy.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoice
    {
        public int Id { get; set; }
        public int IdPurchase { get; set; }
        public decimal TotalAmount { get; set; }
        public int InvoiceNumber { get; set; }
        public string PaymentMethod { get; set; }

        [JsonIgnore]
        public virtual Purchase Purchase { get; set; }
    }
}
